removePathAccents = true
buildFuture = true
paginatePath = "page"
paginate = 12
disableKinds = ["RSS", "section"]
pygmentsCodefences = true
copyright = "2021 by lernblog.org - Creative Commons Attribution-ShareAlike 4.0"

[params]
lernblogName = "Lernblog"
lernblogVersion = "1.5.0"
lernblogUrl = "https://www.lernblog.org"

[permalinks]
posts = "/:filename/"
pages = "/:filename/"

[taxonomies]
tag = "tags"

[outputs]
home = ["HTML", "ATOM", "JSON"]

[mediaTypes."application/atom+xml"]
suffixes = ["xml"]

[outputFormats.ATOM]
mediaType = "application/atom+xml"
baseName = "index"
isPlainText = false

[markup.goldmark.renderer]
unsafe= true